### ISSUE TITLE
WE NEED A NAME FOR THIS THING

### ISSUE THREAD

**Issue by jackhammer2042** [CoderDojo-Ennis/HybernRPG#1]

**Comment by Sethanic** [comment]
Swap?

**Comment by JammySquirrel** [comment]
I like the name "swap". I've done a quick search on steam and on the Google play store, and nothing has came up with the same name. However, I propose the title is
"SWAP"
in all capitals.
It looks nice, and sums up the heart of the game.
How does everyone feel?

**Comment by conlaedd** [comment]
SWAP would be cool, especially if we made it into an acronym somehow

**Comment by fionnphotography** [comment]
How about SWAP CHILD. Assuming the character is young.

**Comment by conlaedd** [comment]
Sounds kinda like it's related to kidnapping

**Comment by Conlaed** [comment]
Hey this is my real account i had accidentally made 2

**Comment by JammySquirrel** [comment]
SWAP CHILD does sound somewhat kidnapp-y.
I think we should just go for SWAP.

**Comment by JammySquirrel** [comment]
Name of game:
SWAP
