### ISSUE TITLE
Random graphical glitches

### ISSUE THREAD

**Issue by JammySquirrel** [CoderDojo-Ennis/HybernRPG#11]
I compiled a copy of the game and tested it, but I noticed a graphics glitch. For some reason, black stripes occasionally appear in the upper right corner and disappear after a split second.

**Comment by Sethanic** [comment]
I can't reproduce this problem, but I have noticed that on simple graphics or less there is a sudden increase in the speed of the laser cultist's arm movement.

**Comment by JammySquirrel** [comment]
I'm closing this issue to neaten things up. This particular graphics glitch hasn't appeared since, and the bombardier and laser cultist problems have been fixed. (I think)
