### ISSUE TITLE
(So much for using slack as our communication) hub

### ISSUE THREAD

**Issue by jackhammer2042** [CoderDojo-Ennis/HybernRPG#12]
So ask on coder side chances of linking to game objects so when one's state changes it effects the other 
I.e. Slapy cultist alive wall is spawned in he dies wall despawns Problem being how do you code that "Link" or is this a stupid question 

Also I asked this question just a lot worse in slack hence title

**Comment by jackhammer2042** [comment]
Now some may ask why the bracket in the title the answer I hate my phone Sometimes

**Comment by JammySquirrel** [comment]
`
//This value is assigned in the inspector
//It give reference to the cultist game object in question

GameObject cultist

Update()
{
        if(cultist == null)
        {
                //cultist has been deleted
               DespawnWall();
        }
}
`
