### ISSUE TITLE
Nuclear Mushrooms

### ISSUE THREAD

**Issue by Sethanic** [CoderDojo-Ennis/HybernRPG#14]
No movement.
Fires upwards or at the player; ask Jack.

**Comment by sparpo** [comment]
Where should i make  the shrooms? (In what scene i mean)

**Comment by jackhammer2042** [comment]
as of now unity is being an asshole and doesn't want me getting into the
game now I don't care specifically where it goes in the current build for
as I understand the current build is just a sand box for testing and the
actual levels will be put together at a later hopefully soon date.

so the answer is where ever it just needs to become an asset so we can
place it  where ever we want later if that makes sense the initial
"birthplace" I guess doesn't matter as long as it becomes an asset

so yea whatevs easiest

**Comment by JammySquirrel** [comment]
Nuclear mushroom explodes once the player gets too close. Actual explosion effect still to be added at later point.
