### ISSUE TITLE
Make the wheel FUN

### ISSUE THREAD

**Issue by JammySquirrel** [CoderDojo-Ennis/HybernRPG#55]
Buttons make a "boop" noise and grow larger when you hover over them. Clicking them also results in something noticeable, a sound and/or the button changing colour or changing size again. Interacting with the menu should be satisfying; players are going to do it a lot as it's used to swap limbs, the core mechanic of the game.

**Comment by Sethanic** [comment]
* OnEventManager

**Comment by JammySquirrel** [comment]
Wheel is now suitably satisfying to use.
