### ISSUE TITLE
Grappling Hook Issue!

### ISSUE THREAD

**Issue by fionnphotography** [CoderDojo-Ennis/HybernRPG#59]
When I was playing the game in the "GameDemo" scene the grappling hook seemed to glitch every now and then. I would aim it at one place and then the next it might hook onto something completely different.

**Comment by JammySquirrel** [comment]
There are a few glitches present with the grappling hook, but I think I've fixed the one you're talking about. Whenever the hook hit a projectile it grabbed onto it, which caused the grappling hook to be destroyed by the projectile. After it was destroyed a new grappling hook was automatically created, which would default to a position of (0, 0), pulling the the player towards that point.

**Comment by JammySquirrel** [comment]
It took about an hour of work, but I finally managed to edit the grappling hook script to prevent this from happening. Keep an eye on things though, as similar problems may arise.
