### ISSUE TITLE
I think we need to reorganise the assets

### ISSUE THREAD

**Issue by sparpo** [CoderDojo-Ennis/HybernRPG#60]
I find it quite difficult to find certain sprites/scripts/prefabs. I just think we could change the system. Anyone  else agree?

**Comment by Sethanic** [comment]
Perhaps one folder for all art and various sub folders for player, enemies, UI, etc. within would work best.

**Comment by JammySquirrel** [comment]
Has anyone started this? We could also have a folder dedicated to assets for building levels, which contains all the enemys, the player and the terrain which are required for building a level.

**Comment by Sethanic** [comment]
We already have an add-to-scene folder under Prefabs for that, but I'm not sure if the player or any terrain is under there.

**Comment by JammySquirrel** [comment]
I propose we broadly organise things into the following folders: General, Menu, World1, World2, World3, World4, World5. Enemies and assets are sorted into the world they first appear in or where they are most used.

**Comment by Sethanic** [comment]
I think enemies should have their own folder so they can be found easily.

**Comment by JammySquirrel** [comment]
We could put an "Enemies" under General then.

**Comment by Sethanic** [comment]
That works. What else would be under general, UI and such?

**Comment by JammySquirrel** [comment]
UI, Player, the portal, anything that doesn't really fit in a specific world.

**Comment by JammySquirrel** [comment]
Okay, it's reorganised.  I encourage everyone to become familiar with the new folder arrangement.  We haven't really been using a single system for organising UI stuff as we've been working, so people may want to make tweaks to how it's laid out.
