### ISSUE TITLE
"actual star wrekin" level edited

### ISSUE THREAD

**Issue by QuinnPainter** [CoderDojo-Ennis/HybernRPG#73]
Has some good ideas, but needs to be restructured as it is unclear where to go.

**Comment by GeekyMonkey** [comment]
Have ye got any visual indicators of the path options at all?

**Comment by QuinnPainter** [comment]
Not really, no.

**Comment by GeekyMonkey** [comment]
Could Road signs or arrows with icons be an option? Or a minimap?  or initial level zoom out preview?

**Comment by QuinnPainter** [comment]
Maybe. Regardless, I still feel the level needs a bit of a re-do.

**Comment by JammySquirrel** [comment]
Perhaps if the portal is visible from the start position. Then the player
has a strong sense of their goal.

**Comment by JammySquirrel** [comment]
Done!
