### ISSUE TITLE
Shield level doesn't really introduce shield

### ISSUE THREAD

**Issue by JammySquirrel** [CoderDojo-Ennis/HybernRPG#77]
The first time you encounter the laser cultists, they're aiming at you from up high. It doesn't really fulfill the purpose of introducing the shield mechanics.

**Comment by QuinnPainter** [comment]
What do you mean? How do you think the shield should be introduced?

**Comment by JammySquirrel** [comment]
Well, you should definitely be able to see the laser cultist when you first encounter lasers. Maybe, there is piece of terrain blocking his line of sight to you. Then, when you move over it, he can see you and attacks, teaching the player about the dangers of lasers. Then they'll have to figure out that the shield can block them.

**Comment by GeekyMonkey** [comment]
Probably with the first baddie shooting at your shield so you can see it working.
