### ISSUE TITLE
LIMB SWAP MENU BROKEN

### ISSUE THREAD

**Issue by JammySquirrel** [CoderDojo-Ennis/HybernRPG#86]
Currently only stays open if you hold down right click, making it difficult to choose a limb. Also, jetpack, when selected, no longer functions for some reason. Perhaps related to controller support? Conlaed says hi, btw.

**Comment by QuinnPainter** [comment]
Limb swap menu change is intentional, you are meant to hold right button, put mouse over limb and release right button to select. Made this change to help controller support. Can change it back if you want. Will also look into the jetpack thing.

**Comment by GeekyMonkey** [comment]
You could have it do both.  So a click and release without moving the mouse far toggles it open and closed, but a click and drag automatically closes when released.

**Comment by JammySquirrel** [comment]
The problem with the shield probably ties in with the addition of controller support. The code for the jetpack times the number of frames until the button for jumping is released. Now that there's more than one button input for jumping, it's confusing it, I guess. It works fine using space, but not using w.

**Comment by QuinnPainter** [comment]
Jetpack fixed to use seconds instead of frames, however values for strength and time may be wrong, so feel free to tweak
