### ISSUE TITLE
Grappling Hook

### ISSUE THREAD

**Issue by Sethanic** [CoderDojo-Ennis/HybernRPG#9]
I'm fairly sure it should drag both the enemy and player together and meet in the middle. Right now, if the player is blocked and grappled to an enemy, the enemy won't close the gap to the player.

**Comment by JammySquirrel** [comment]
Hmm... yes. I think I know how to fix that, but I'll do it once we get the other stuff necessary for the milestone done.

**Comment by JammySquirrel** [comment]
I don't think this is really necessary. The game works fine with the current grappling hook behaviour, and we'd have to retest all our combat scenarios if you can pull enemies.
